GpupoCamelSpiderBundle_subscription:
    resource: "@GpupoCamelSpiderBundle/Resources/config/routing/subscription.yml"
    prefix:   /subscription

GpupoCamelSpiderBundle_news:
    resource: "@GpupoCamelSpiderBundle/Resources/config/routing/news.yml"
    prefix:   /news

GpupoCamelSpiderBundle_rawnews:
    resource: "@GpupoCamelSpiderBundle/Resources/config/routing/rawnews.yml"
    prefix:   /rawnews

GpupoCamelSpiderBundle_newstag:
    resource: "@GpupoCamelSpiderBundle/Resources/config/routing/newstag.yml"
    prefix:   /newstag

GpupoCamelSpiderBundle_category:
    resource: "@GpupoCamelSpiderBundle/Resources/config/routing/category.yml"
    prefix:   /category

GpupoCamelSpiderBundle_stars:
    resource: "@GpupoCamelSpiderBundle/Resources/config/routing/stars.yml"
    prefix:   /stars

