parameters:
    camel_spider.laucher.class: Gpupo\CamelSpiderBundle\Launcher
    camel_spider.processor.class: CamelSpider\Spider\Processor
services:

    camel_spider.processor:
        class: %camel_spider.processor.class%
        arguments: [@goutte]
    camel_spider.launcher:
        class: %camel_spider.laucher.class%
        arguments: [@camel_spider.processor]
