parameters:
#    gpupo_camel_spider.example.class: Gpupo\CamelSpiderBundle\Example

services:
#    gpupo_camel_spider.example:
#        class: %gpupo_camel_spider.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
