<?php

namespace Gpupo\CamelSpiderBundle\Entity;

use Doctrine\ORM\EntityRepository,
    Gpupo\CamelSpiderReaderBundle\Entity\InterfaceNode;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository implements InterfaceNode
{
    public function findForMenu()
    {
        return $this->findBy(array(), array('name'=>'ASC'));
    }

    public function findForList()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.parent IS NOT NULL')
            ->add('orderBy', 'c.lft ASC');
        return $qb->getQuery()->getResult();
    }

}
