<?php

namespace Gpupo\CamelSpiderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsVoteRepository extends EntityRepository
{

    public function getAverageById($news_id)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->add('select', $qb->expr()->avg('a.value'))
            ->add('where', $qb->expr()->eq('a.news', '?1'))
            ->setParameter(1, $news_id);

        return $qb->getQuery();
    }

}
