<?php

namespace Gpupo\CamelSpiderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{

    public function queryBuilder()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.moderation = :moderation')
            ->add('orderBy', 'a.createdAt DESC');
        return $qb;
    }
    public function findByType($type, $id)
    {
        $q = $this->queryBuilder();
        $q->andWhere('a.'.strtolower($type) . ' = :tid')
            ->setParameters(array('moderation' => 'APROVED', 'tid' => $id));
        return $q->getQuery();
    }
}
