<?php

namespace Gpupo\CamelSpiderBundle\Entity;

use Doctrine\ORM\EntityRepository,
    Gpupo\CamelSpiderReaderBundle\Entity\InterfaceNode;
/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository implements InterfaceNode
{
    public function findByActiveSubscriptions()
    {
        return $this->findBy(array('isActive'=> true));
    }

    public function findForMenu()
    {
        return $this->findBy(array('isActive'=> true), array('name'=>'ASC'));
    }
}
