newssource:
    pattern:  /
    defaults: { _controller: "GpupoCamelSpiderBundle:NewsSource:index" }

newssource_show:
    pattern:  /{id}/show
    defaults: { _controller: "GpupoCamelSpiderBundle:NewsSource:show" }

newssource_new:
    pattern:  /new
    defaults: { _controller: "GpupoCamelSpiderBundle:NewsSource:new" }

newssource_create:
    pattern:  /create
    defaults: { _controller: "GpupoCamelSpiderBundle:NewsSource:create" }
    requirements: { _method: post }

newssource_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GpupoCamelSpiderBundle:NewsSource:edit" }

newssource_update:
    pattern:  /{id}/update
    defaults: { _controller: "GpupoCamelSpiderBundle:NewsSource:update" }
    requirements: { _method: post }

newssource_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GpupoCamelSpiderBundle:NewsSource:delete" }
    requirements: { _method: post }
