
stars_submit:
    pattern:  /submit.{_format}
    defaults: { _controller: "GpupoCamelSpiderBundle:Stars:submit", _format: html}
    requirements: { _method: post}

stars_test:
    pattern:  /{news_id}/{rate}/test
    defaults: { _controller: "GpupoCamelSpiderBundle:Stars:submitTest" }

